services:
  - type: web
    name: quiz-app
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
      - key: DB_HOST
        fromService:
          type: pserv
          name: quiz-app-db
          property: host
      - key: DB_NAME
        value: quiz_app
      - key: DB_USER
        value: quiz_user
      - key: DB_PASS
        fromService:
          type: pserv
          name: quiz-app-db
          envVarKey: MYSQL_PASSWORD

  - type: pserv
    name: quiz-app-db
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile.mysql
    envVars:
      - key: PORT
        value: 3306
      - key: MYSQL_DATABASE
        value: quiz_app
      - key: MYSQL_USER
        value: quiz_user
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
